{% raw %}
##
# Db creation
##
---
    - name: install python-mysqldb
      become: true
      become_method: sudo
      apt: name=python-mysqldb state=present

    - name: create database
      become: true
      become_method: sudo
      mysql_db:
        name={{ db_name }}
        encoding=utf8
      notify: restart db service
{% endraw %}
