{% raw %}
##
# Db creation
##
---
    - name: install mysql-server
      become: true
      become_method: sudo
      apt: name=mysql-server state=present

    - name: install python3-pymysql
      become: true
      become_method: sudo
      apt: name=python3-pymysql state=present

    - name: create database
      become: true
      become_method: sudo
      mysql_db:
        name={{ db_name }}
        encoding=utf8
      notify: restart db service
{% endraw %}
