# Generated by Django 2.1.7 on 2019-04-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treenav', '0002_auto_20151001_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='label_it',
            field=models.CharField(help_text='The display name on the web site.', max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='label',
            field=models.CharField(help_text='The display name on the web site.', max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.CharField(blank=True, help_text='The view of the page you want to link to, as a python path or the shortened URL name.', max_length=255, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(help_text='Unique identifier for this menu item (also CSS ID)', max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
