# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 09:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='content')),
                ('template_name', models.CharField(blank=True, help_text="Example: 'pages/contact_page.html'. If this isn't provided, the system will use 'pages/default.html'.", max_length=70, verbose_name='template name')),
                ('registration_required', models.BooleanField(default=False, help_text='If this is checked, only logged-in users will be able to view the page.', verbose_name='registration required')),
                ('enable_social_sharing', models.BooleanField(default=False, verbose_name='enable social sharing')),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('meta_title', models.CharField(blank=True, help_text='default to page title', max_length=200, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, help_text='default to first 20 words of content', null=True, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='default to page tags', max_length=200, null=True, verbose_name='meta keywords')),
                ('sites', models.ManyToManyField(to='sites.Site', verbose_name='sites')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='comma separated values', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
            ],
            options={
                'ordering': ('url',),
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
    ]
