# Generated by Django 3.2.2 on 2021-05-14 15:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='content')),
                ('template_name', models.CharField(blank=True, help_text="Example: 'pages/contact_page.html'. If this isn't provided, the system will use 'pages/default.html'.", max_length=70, verbose_name='template name')),
                ('registration_required', models.BooleanField(default=False, help_text='If this is checked, only logged-in users will be able to view the page.', verbose_name='registration required')),
                ('enable_social_sharing', models.BooleanField(default=False, verbose_name='enable social sharing')),
                ('status', models.IntegerField(choices=[(1, 'bozza'), (2, 'pubblicato'), (3, 'archiviato')], default=1)),
                ('meta_title', models.CharField(blank=True, help_text='default to page title', max_length=200, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, help_text='default to first 20 words of content', null=True, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='default to page tags', max_length=200, null=True, verbose_name='meta keywords')),
                ('parent', models.ForeignKey(blank=True, help_text='Used to compose breadcrumbs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page', verbose_name='parent')),
                ('sites', models.ManyToManyField(to='sites.Site', verbose_name='sites')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='comma separated values', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ('url',),
            },
        ),
    ]
