# Generated by Django 2.2 on 2019-07-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Used to compose breadcrumbs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.Page', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.IntegerField(choices=[(1, 'bozza'), (2, 'pubblicato'), (3, 'archiviato')], default=1),
        ),
    ]
